"""Backward-compatible shim — use ``entity_knowledge``."""

from __future__ import annotations

from novel_mcp.entity_knowledge import (
    DEPTH_RANK,
    KNOWLEDGE_RELATIONS,
    PLR_KNOWS_RELATION,
    build_knowledge_view,
    can_show_canonical_name,
    can_speak_about,
    can_speak_entity_name,
    depth_from_attrs,
    depth_rank,
    entity_kind,
    entity_labels_from_warm,
    entity_refs_missing_from_warm,
    format_knowledge_hud,
    holder_knows_entity,
    knowledge_gate_hint,
    knowledge_meta,
    knowledge_record,
    load_holder_knowledge,
    load_holder_knowledge_from_warm,
    merge_knowledge_index,
    merge_warm_catalog_lines,
    npc_anonymous_label,
    parse_warm_knowledge,
    plr_knows_character,
    resolve_biz_display,
    resolve_npc_display_name,
    resolve_place_display_name,
)

__all__ = [
    "DEPTH_RANK",
    "KNOWLEDGE_RELATIONS",
    "PLR_KNOWS_RELATION",
    "build_knowledge_view",
    "can_show_canonical_name",
    "can_speak_about",
    "can_speak_entity_name",
    "depth_from_attrs",
    "depth_rank",
    "entity_kind",
    "entity_labels_from_warm",
    "entity_refs_missing_from_warm",
    "format_knowledge_hud",
    "holder_knows_entity",
    "knowledge_gate_hint",
    "knowledge_meta",
    "knowledge_record",
    "load_holder_knowledge",
    "load_holder_knowledge_from_warm",
    "merge_knowledge_index",
    "merge_warm_catalog_lines",
    "npc_anonymous_label",
    "parse_warm_knowledge",
    "plr_knows_character",
    "resolve_biz_display",
    "resolve_npc_display_name",
    "resolve_place_display_name",
]
